### ISSUE TITLE
month picker remaining open always 

### ISSUE THREAD

**Issue by shakhawatfci** [kleinrein/vue-month-picker#30] opened 2020-07-09 10:31 UTC
i have used in with modal but month picker not closing always remaining open .. and if i use it in form when pressing next year button form getting submited .

**Comment by kleinrein** [comment] 2020-07-09 20:26
Is the modal a custom one? Are you using the <month-picker-input> or only <month-picker>? The form submit issue was fixed in the newly released version 1.2.6.

**Comment by shakhawatfci** [comment] 2020-07-11 03:25
Modal is bootstrap modal but it’s not closing outside of modal too

**Comment by kleinrein** [comment] 2020-07-15 20:21
Doesn't it close when you click somewhere outside or selecting a month?

**Comment by shakhawatfci** [comment] 2020-07-16 05:09
no it's not clearing and it's the problem ...

**Comment by kleinrein** [comment] 2020-08-17 22:00
Hmm, I'm not sure. Could you reproduce it in a codepen or something? Could be hacked by closing it with a flag on the change function but that's not optimal.

**Comment by kleinrein** [comment] 2020-08-29 22:24
Closing due to inactivity. Reopen if the issue still occurs.

**Closed by kleinrein** 2020-08-29 22:24 UTC
